### ISSUE TITLE
인코딩 타입에 gzip 적용

### ISSUE THREAD

**Issue by jerry92k** [jerry92k/yssmap#19]
네트워크 트래픽 감소와 응답 속도 향상을 위해 Content-Encoding: gzip 적용 필요

**Comment by jerry92k** [comment]
## 적용 완료
```yml
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 2048
```
